name: Release Automation

on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Changelog
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD^)
        echo "Generating changelog since $LAST_TAG"
        git log --pretty=format:"- %s" $LAST_TAG..HEAD > CHANGELOG.md

    - name: Build Project
      run: |
        echo "Run your build commands here"
        mkdir build && echo "Sample Build Artifact" > build/artifact.txt

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: ./build

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/artifact.txt
        asset_name: artifact.txt
        asset_content_type: text/plain
